name: Run Jest Tests on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test -- ./src/__test__/recommend.test.js ./src/__test__/Signup.test.js
