name: Jest Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        working-directory: ${{ github.workspace_path }}/Application_SE02/front-end
        run: npm install --legacy-peer-deps
      - name: Run Jest tests
        working-directory: ${{ github.workspace_path }}/Application_SE02/front-end
        run: npm test -- --testPathPattern=".*" && exit 0
